import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>CreateApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl text-yellow-50 text-center bg-slate-700 font-bold underline">
        sdfdf
      </h1>
    </div>
  );
};

export default Home;
